language: generic
sudo: required
services:
  - docker

before_start:
  - docker build -t rlmf82/docker-complex -f ./docker-react/Dockerfile.dev ./docker-react
  
script:
  - docker run -e CI=true rlmf82/docker-complex npm run test -- --coverage

after_success:
  - docker build -t rlmf82/docker-react ./docker-react
  - docker build -t rlmf82/docker-nginx ./nginx
  - docker build -t rlmf82/docker-server ./server
  - docker build -t rlmf82/docker-worker ./worker

  # Log docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push rlmf82/docker-react
  - docker push rlmf82/docker-nginx
  - docker push rlmf82/docker-server
  - docker push rlmf82/docker-worker
