version: '3'
services:
  nginx:
    depends_on:
      - api
      - docker-react
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  ##postgres:
    ##image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres 
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD='postgres'
      - PGPORT=5432
  docker-react:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./docker-react
    volumes:
      - /app/node_modules
      - ./docker-react:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379